//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public int FileType { get; set; }
        public string FileDescription { get; set; }
        public bool IsDeleted { get; set; }
        public int LangId { get; set; }
    }
}
