//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int Id { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Code { get; set; }
        public string Nationality { get; set; }
        public string NationalityEn { get; set; }
        public string TwoLetterCode { get; set; }
    }
}
