//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorsLog
    {
        public int Id { get; set; }
        public string ErrorMessage { get; set; }
        public string Link { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
        public string UserAgent { get; set; }
        public string RequestType { get; set; }
        public string PostedData { get; set; }
        public bool IsSolved { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public bool IsAjax { get; set; }
    }
}
