//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public int MediaType { get; set; }
        public string Caption { get; set; }
        public int MediaAlbumId { get; set; }
        public bool IsInMainPage { get; set; }
        public string ExternalLink { get; set; }
        public bool IsDeleted { get; set; }
        public string CaptionEn { get; set; }
    
        public virtual MediaAlbum MediaAlbum { get; set; }
    }
}
