//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergartenNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string Link { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public bool InMenu { get; set; }
        public bool ForAdmin { get; set; }
        public bool NeedLogin { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Icon { get; set; }
        public Nullable<int> TypeId { get; set; }
        public virtual Page Parent { get; set; }
        public virtual List<Page> ChildPages { get; set; }
    }
}
